const assert=require('assert/strict');const fs=require('fs');const path=require('path');const service=require('../src/services/laundryReports.service');const repository=require('../src/repositories/laundryReports.repository');const {parseRequest,dateRangeQuerySchema,resortReportQuerySchema}=require('../src/validators/laundryReports.validator');const {prisma}=require('../src/core/prisma');
const manager={userId:1,role:'LAUNDRY_MANAGER',workspaceType:'LAUNDRY',active:true};const originals={overview:repository.overview,trends:repository.trends,resorts:repository.resorts,items:repository.items,issues:repository.issueSummary};
async function main(){
 const today=service.resolveRange({start:'2026-07-14',end:'2026-07-14'});assert.equal(today.start.toISOString(),'2026-07-13T17:00:00.000Z');assert.equal(today.endExclusive.toISOString(),'2026-07-14T17:00:00.000Z');assert.equal(today.timezone,'Asia/Bangkok');
 assert.equal(service.resolveRange({start:'2026-07-08',end:'2026-07-14'}).days,7);assert.equal(service.resolveRange({start:'2026-06-15',end:'2026-07-14'}).days,30);
 assert.throws(()=>service.resolveRange({start:'2026-07-15',end:'2026-07-14'}),error=>error.statusCode===400);assert.throws(()=>service.resolveRange({start:'2025-01-01',end:'2026-07-14'}),error=>error.statusCode===400);assert.throws(()=>parseRequest(dateRangeQuerySchema,{start:'bad',end:'2026-07-14'}),error=>error.statusCode===400);
 repository.overview=async()=>({totalWorks:7,statuses:[{currentStatus:'DATA_RECORDED',_count:{_all:2}},{currentStatus:'CLOSED',_count:{_all:3}},{currentStatus:'CANCELLED',_count:{_all:2}}],totalResorts:2,totalBags:4,totalItemCount:50,totalWeightKg:12.5,issues:[{status:'OPEN',_count:{_all:2}}],claims:[{status:'OPEN',_count:{_all:1}}]});
 const overview=await service.getOverview({start:'2026-07-01',end:'2026-07-14'},{actor:manager});assert.equal(overview.metrics.readyWorks,2);assert.equal(overview.metrics.pendingWorks,2);assert.equal(overview.metrics.closedWorks,3);assert.equal(overview.metrics.activeClaims,1);
 await assert.rejects(()=>service.getOverview({}, {actor:{...manager,role:'LAUNDRY_STAFF'}}),error=>error.statusCode===403);
 repository.trends=async()=>[];assert.deepEqual((await service.getTrends({}, {actor:manager})).items,[]);
 repository.resorts=async()=>[{resortId:1,resortName:'A',totalWorks:2,activeWorks:1,closedWorks:1,bags:3,itemCount:8,issueCount:1},{resortId:2,resortName:'B',totalWorks:5,activeWorks:2,closedWorks:3,bags:7,itemCount:20,issueCount:2}];
 const resorts=await service.getResorts({take:'1',skip:'0',sort:'totalWorks',order:'desc'},{actor:manager});assert.equal(resorts.items[0].resortName,'B');assert.equal(resorts.pagination.total,2);
 assert.throws(()=>parseRequest(resortReportQuerySchema,{take:'0',hack:'x'}),error=>error.statusCode===400);
 const routes=fs.readFileSync(path.resolve(__dirname,'../src/routes/laundryReports.routes.js'),'utf8');assert.equal(/post|patch|put|delete/i.test(routes),false);for(const endpoint of ['overview','trends','resorts','items','issues'])assert.match(routes,new RegExp(`'/${endpoint}'`));
 const repo=fs.readFileSync(path.resolve(__dirname,'../src/repositories/laundryReports.repository.js'),'utf8');assert.match(repo,/weightPerPieceKg/);assert.match(repo,/WorkStatusLog/);assert.match(repo,/take:5/);console.log('REPORTS_VERIFY PASS');
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{repository.overview=originals.overview;repository.trends=originals.trends;repository.resorts=originals.resorts;repository.items=originals.items;repository.issueSummary=originals.issues;await prisma.$disconnect();});
